spring.application.name=Examen_5_6_AD_SergioArjona

# Configuracion de conexion a MongoDB Atlas
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=Tienda

spring.data.mongodb.auto-index-creation=true